MontgomeryLab/tinyRNA

- .travis.yml
- environment.yml
- requirements.txt
- setup.py
- tests/setup_test.sh
- tests/time_collapser.py
- tests/time_counter.py
- tests/unit_tests_counter.py
This is specifically for pre-existing unit tests. The test file `unit_tests_counter` currently tests methods which are not defined in aquatx.srna.counter, but this will be updated in a later issue after some investigation.
Closes #7
> Update package imports for current package structure

- environment.yml
> Bugfix for bowtie dependency issue

- setup.py
> Setup script issue resolved

- START_HERE/run_config.yml
- aquatx/aquatx.py
- aquatx/cwl/tools/aquatx-deseq.cwl
- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/organize-outputs.cwl
- aquatx/extras/run_config_template.yml
- aquatx/srna/Configuration.py
- aquatx/srna/aquatx-deseq.r
- tests/testdata/run_config_template.yml
PCA plots can now be produced for each comparison. Plots are PDF vector graphics via trellis for proper handling of the lattice plots produced by DESeq2's `plotPCA()` function
Closes #51
> PCA plot option added to the DGE step

- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/organize-outputs.cwl
This PR resolves further issues encountered with CWL's handling of Counter diagnostic outputs. It also cleans up the handling of optional inputs for organize-outputs.cwl
> CWL improvements and bugfixes for Counter diagnostics

- tiny/rna/counter/counter.py
- tiny/rna/counter/feature_selector.py
- tiny/rna/counter/hts_parsing.py
The semantics of the strand selector have been corrected following recent discussions with Tai. The issue will remain open while these changes are tested and verified.
> Strand selection semantics corrected

- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/matching.py
- tiny/rna/counter/statistics.py
Counter's feature_counts.csv output table now displays all features which match an identity rule, regardless of count, and regardless of whether they had any associated alignments.
PR includes other detail improvements, including comment updates and type hint corrections, for the Counter subpackage.
> Counter: feature representation corrections

- MANIFEST.in
- environment.yml
- setup.py
- tiny/rna/resume.py
- tiny/rna/tiny-deseq.r
Installation issues stemming from updates in installer dependencies (setuptools and pip) have been resolved.
> Installation issues addressed & minor bugfixes in replot and tiny-deseq.r

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/statistics.py
- tiny/templates/run_config_template.yml
> New command line option for Counter: --no-normalize

- START_HERE/features.csv
- START_HERE/run_config.yml
- tiny/cwl/tools/tiny-deseq.cwl
- tiny/entry.py
- tiny/rna/configuration.py
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/util.py
> Detail updates for Configuration, Plotter, run config and features sheet

- tiny/cwl/tools/tiny-deseq.cwl
- tiny/entry.py
- tiny/rna/plotter.py
> cwltool-related URL encoding workaround removed

- README.md
Minor formatting fix in the table of contents
> README minor formatting fix

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/configuration.py
- tiny/templates/run_config_template.yml
> Support for low DF experiment design

- CHANGELOG.md
- setup.sh
- tiny/rna/plotter.py
> Various minor bugfixes in Counter, Plotter, and setup.sh

- CHANGELOG.md
- START_HERE/paths.yml
- START_HERE/run_config.yml
- tests/testdata/paths.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/fastp.cwl
- tiny/cwl/workflows/preprocessing.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/entry.py
- tiny/rna/configuration.py
- tiny/templates/paths.yml
- tiny/templates/run_config_template.yml
The following default value has been changed:
- average_qual: 35 -> 25
The following configuration options have been added:
- trim_front1
- trim_tail1
- adapter_fasta
Closes #141
> New fastp options

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/templates/run_config_template.yml
This PR addresses the following new bugs added to issue-142:
- DGE: a Samples Sheet without a control condition will cause the DGE step to crash. This is due to an incorrect default value in the Run Config files
- Plotter: class proportions for class_charts are improperly calculated
- Plotter: the table in class_charts shows 2 digit decimal precision but will never display anything but integer precision
> Bugfixes: DGE no-control experiments, Plotter corrections to class_charts

- tiny/rna/counter/counter.py
- tiny/rna/counter/statistics.py
- Normalization by loci count is performed even when running with the --no-normalization option
- Alignment stats are now correctly counted when running with the --no-normalization option
Closes #163 
Closes #172
> Counter: fixes for --no-normalization option

- tiny/rna/tiny-deseq.r
> tiny-deseq: Feature Name alias column is appended to output tables

- tests/unit_tests_features.py
- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/statistics.py
SummaryStats has been successfully refactored into purposed classes with an abstract base class for sharing global attributes and helper functions. This approach is substantially cleaner.
Unit tests related to IntervalSelectors currently fail only due to structural changes to selection outputs which support counting by rule. I'm leaving these as-is for now since we are still ironing out the extent to which we want to count by rule
Closes #180
> Counter: SummaryStats refactored to MergedStatsManager

- README.md
This PR simply removes the "work in progress" warnings from the header in README.md. All other v1.0.0 preparation tasks are complete.
> Final preparation for v1.0.0 release

- START_HERE/features.csv
- START_HERE/reference_data/features.csv
Updated features.csv with "Classify as..." information and changed miRNA Overlap to "5' anchored".
> Update features file for ram1 data

- README.md
> v1.2 version bump in README.md's installation section

- setup.py
- tiny/rna/resume.py
- tiny/templates/tinyrna-light.mplstyle
The following changes were asked to be included in the v1.2 release:
- Resume Run Config files are now timestamped
- Default plot styles have been changed
- setup.py has been modified in preparation for tiny-count standalone installation via bioconda
Closes #231
> v1.2 patch: additional updates

- tests/unit_tests_plotter.py
- tiny/rna/plotterlib.py
- Improved support for a larger number of classes in DGE class scatter plots
- If the number of classes exceeds the number of available colors, a helpful error is produced
> tiny-plot: extended support for large numbers of classes in DGE class scatter plots
