MontgomeryLab/tinyRNA

- aquatx/aquatx.py
- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/per-library.cwl
- aquatx/extras/run_config_template.yml
- aquatx/srna/counter.py
- environment.yml
- tests/testdata/run_config_template.yml
- tests/unit_tests_aquatx.py
Closes #28 
Adds 
- Options to use Python-native use of cwltool, rather than invoking cwltool via the command line
- Parallel execution of the pipeline via the cwltool runner (Python-native mode only to allow for greater control over concurrency in later development)
- Redesigned pipeline workflow. The pipeline now executes library-by-library for fastp, bowtie, and collapser. This will result in much better runtimes for sample sets with large differences in length.
Fixes:
- cwltool is now able to properly collect output files with special characters in their name. Previously this had caused the pipeline to fail at the Counter step since 5' NT/length tables are written to filenames containing parentheses. See note about toil[cwl] in remaining issues below
Remaining issues
- The current …
> Better workflow concurrency

- START_HERE/run_config.yml
- aquatx/cwl/tools/aquatx-count.cwl
- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/organize-outputs.cwl
- aquatx/extras/run_config_template.yml
- aquatx/srna/counter/FeatureSelector.py
- aquatx/srna/counter/counter.py
- aquatx/srna/counter/hts_parsing.py
- aquatx/srna/counter/statistics.py
- aquatx/srna/resume.py
- tests/testdata/run_config_template.yml
- tests/unit_tests_counter.py
- tests/unit_tests_entry.py
- tests/unit_tests_hts_parsing.py
This PR changes the approach Counter uses to resolve SAM record intervals -> features. This resolution is now strandless. Features parsed from GFF files are stored strandless. Only the SAM record's strand information is retained and used during selection. Previously, features were resolved in a strand-specific way that does not make sense for our strand selection parameters in Features Sheet.
Counter now supports printing detailed diagnostics about eliminations that took place. Two new logfiles are produced with the `-d` command line option:
- {prefix}_alignment_diags.csv
- **Eliminated counts**: when features were associated with an alignment, but none of these features passed selection, this value is incremented by the alignment's corr_count (reads / loci)
- **No feature counts**: when …
> Improvements and fixes for Counter

- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/organize-outputs.cwl
- aquatx/srna/counter/FeatureSelector.py
- aquatx/srna/counter/counter.py
- aquatx/srna/counter/statistics.py
Counter's feature counts table now undergoes an additional filtering step.
Rather than displaying all features parsed from GFF files (including zero count features), we now show only the features that matched an identity rule in the Features Sheet.
- This includes features that have zero counts (due to hierarchy eliminations in phase 1 or elimination in phase 2)
- This does NOT include GFF features that match on identity but were not encountered in SAM alignments
> Improved Counter feature counts table

- START_HERE/run_config.yml
- aquatx/cwl/tools/aquatx-plot.cwl
- aquatx/cwl/tools/make-subdir.cwl
- aquatx/cwl/workflows/aquatx_wf.cwl
- aquatx/cwl/workflows/organize-outputs.cwl
- aquatx/entry.py
- aquatx/extras/run_config_template.yml
- aquatx/srna/aquatx-deseq.r
- aquatx/srna/counter/counter.py
- aquatx/srna/plotter.py
- aquatx/srna/plotterlib.py
- aquatx/srna/resume.py
- tests/testdata/run_config_template.yml
The following terminal warnings/errors have been addressed:
- Characters in DESeq2's design formula
- CWL workflow validation warnings
- UTF-8 locale warnings in Plotter
- Normalization warnings for pie charts in Plotter
The following improvements were made to the pipeline:
- Verbosity preference can now be set in the Run Config. We now have options for `quiet` (no cwltool output, only output from the individual steps), `normal` (the current non-debug output level), and `debug` (detailed information about cwltool operations)
- End-to-end runtime is reported; runtimes reported by steps now have clearer verbiage
- The Paths Sheet is now updated at the end of a _successful_ pipeline run. Previously the Paths Sheet was updated at the end of a run regardless of overall success/fail status
- …
> Terminal output control/cleanup and Plotter improvements

- tiny/cwl/tools/tiny-deseq.cwl
- tiny/rna/plotter.py
- tiny/rna/tiny-deseq.r
- tiny/rna/util.py
This PR introduces the following:
- One PCA plot per run (formerly, one per comparison which is incorrect and redundant)
- Original sample names are preserved in output tables. This is reflected in Plotter's sample labels/titles.
- Plotter no longer expects sanitized sample names
- Relative paths are accepted for the input feature counts csv
- Command line option --drop-zero which drops all rows/features which have a zero count across all libraries
> tiny-deseq has been improved

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/matching.py
- tiny/rna/counter/statistics.py
- tiny/templates/run_config_template.yml
Counter now has the option to show all features in the output counts table, regardless of count, identity rules, or associated alignments.
This PR also cleans up details from previous issues, including the removal of Counter's "intermediate files" option from the CWL.
> Counter: command line arg added for showing all features in output counts

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-deseq.cwl
- tiny/cwl/workflows/organize-outputs.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/tiny-deseq.r
- tiny/templates/run_config_template.yml
- If a control group is not specified, a DGE table is produced for both directions of each pairwise comparison
- PCA plots are now produced using the variance stabilizing transform rather than regularized log transform
- PCA plots are now produced more reliably, and with a 1:1 aspect ratio regardless of PC1/PC2 range
- PCA plots are now placed in the Plotter output directory rather than the DGE output directory
Closes #103
> Deseq: bidirectional DGE tables for all-experimental runs, improved PCA plots

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/resume.py
- tiny/templates/run_config_template.yml
The p-value is used to determine the outgroup (and legend label) in DGE scatter plots. P-values with variable precision are accepted. Values with greater than 4 decimal points of precision are formatted with scientific notation in the plot legend.
Closes #104
> Plotter: optional p-value command line arg added

- tiny/cwl/tools/make-subdir.cwl
- tiny/cwl/workflows/per-library.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/entry.py
- tiny/rna/resume.py
Pipeline startup times have been reduced from 40-60 seconds down to about 17 seconds on my machine. This is the result of simplifying the routine for creating step output subdirectories. To be honest I still can't fathom why it takes 17 whole seconds to validate the workflow and generate its DAG, let alone FORTY TO SIXTY, but... that's somebody else's kitchen.
The design of make-subdir.cwl is vastly better than it was before.
References to Nextflow have been removed from entry.py. This hasn't been a priority or even talked about for months. As far as the associated argparse entry goes, this was essentially just adding an item to the helpstring that we aren't planning to provide anytime soon.
Closes #112
> Improved pipeline start time. More robust handling of output subdirectories.

- tiny/cwl/workflows/per-library.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
The workflow has been modified such that bowtie runs as a scattered CommandLineTool rather than scattering inline with fastp and Collapser. This means that bowtie-build can run during the preprocessing steps for bowtie.
This creates a new problem. Before this change, the pipeline was parallelized library-wise across the fastp, Collapser, and bowtie steps. This meant that as soon as one library completed a step, it was able to move to the next step regardless of which step the other libraries were on. Ultimately all libraries needed to complete the bowtie step before Counter could begin.
Now, all libraries must complete the Collapser step before any of them can proceed to bowtie.
Ultimately the difference this makes is pretty minimal, especially since the same scenario is unavoidable at …
> bowtie-build now runs parallel to fastp, Collapser

- tiny/cwl/tools/tiny-collapse.cwl
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/tools/tiny-plot.cwl
While it would be nice to be able to recover captured STDOUT and STDERR from a pipeline step that fails, cwltool simply doesn't offer a complete solution for this (see https://github.com/common-workflow-language/cwltool/issues/1434 )
Instead we have to supply additional flags to tell the runner to leave outputs in the temporary staging directory, and then infer where these incomplete outputs are among many temporary directories with random names created by cwltool.
Until a better solution is found, STDERR capture will be turned off for our Python utilities so that we can help users diagnose issues.
> STDERR capture turned off for our Python steps

- tiny/rna/counter/statistics.py
The formula for "Mapped Reads" in the summary statistics table has been corrected.
"Aligned Reads" has been changed to "Assigned Reads"
Closes #124
> Bugfix: Counter: summary statistics

- tiny/rna/counter/statistics.py
The following Alignment Stats have been corrected:
- Assigned Single-Mapping Reads
- Assigned Multi-Mapping Reads
- Sequences Assigned to Multiple Features
Sanity checks:
- "Assigned Single-Mapping Reads" + "Assigned Multi-Mapping Reads" == "Total Assigned Reads"
- "Sequences Assigned to Single Feature" + "Sequences Assigned to Multiple Features" == "Total Assigned Sequences"
- "Sequences Assigned to Single Feature" + "Sequences Assigned to Multiple Features" + "Unassigned Sequences" (from Alignment Stats) == "Mapped Sequences" (from Summary Stats)
NOTE:
These issues are only relevant within the context of the Alignment Stats file. The issues and their fixes have no affect on outputs from Counter that are used in downstream analyses.
> All known Alignment Stats flaws have been addressed

- CHANGELOG.md
- tiny/rna/plotter.py
- tiny/templates/tinyrna-light.mplstyle
- Minor bugfix for the DGE-class scatter plot which was omitting Class=unknown groups by default.
- Changed axes title font size to match the axis and tick labels.
> Plotter: "unknown" classes in DGE-class scatterplots, title font size change

- CHANGELOG.md
- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/resume.py
- tiny/templates/run_config_template.yml
The following improvements have been made to class charts:
- The proportion calculation:
- was: `(normalized class count) / (total normalized assigned counts)`
- now: `(raw class count) / (total mapped reads)`
- Due to the change in calculation, an "Unassigned" category has been added
- A table with percentage proportion per class has been added
The following improvements have been made to plotter:
- Subplot caching has been refactored and refined. Cached subplots for each plot type are constructed only during the first attempt at retrieval
- Debug mode is now detected automatically rather than being dictated by the plotterlib constructor parameter
The following bug fixes have been included:
- `tiny replot` now correctly determines if the now-conditional DGE step ran, and adjusts expected …
> Plotter: class charts improvements

- CHANGELOG.md
- tiny/entry.py
Temporary files are now removed at the end of each pipeline run when running `tiny {run|recount|replot}` commands
Closes #140
> Temporary file issue resolved

- .github/workflows/ci-tests.yml
- CHANGELOG.md
- tests/unit_tests_plotter.py
- tiny/rna/plotterlib.py
The "unassigned" category in class charts will currently fail to be included when the proportion is very small. In these cases the other classes will sum to 99.99%. I've taken care to ensure that the solution adapts to the scale incase we want to increase or decrease the decimal precision of the table percentages.
Unit tests have been added for this subject and for the calculation of class counts for features with multiple associated classes.
> Bugfix: floating point arithmetic error causing improper omission of "unassigned" category in class_charts

- tests/unit_test_helpers.py
- tests/unit_tests_counter.py
- tests/unit_tests_features.py
- tests/unit_tests_hts_parsing.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
Closes #148 
Additionally, in some cases subintervals of discontinuous features can wind up being defined adjacent to each other after processing. This happens when the adjacent intervals are defined under unique feature IDs but share the same root parent; this results in two side-by-side intervals with the root parent's feature ID. 
`StepVector.get_steps(merge_values=True)` will remedy this by merging the adjacent intervals but there are two issues with this:
1. Merging is performed by value. Now that start/stop coordinates are included in the feature record tuple, which is what is stored in the StepVector, the adjacent tuples will contain their subinterval coordinates and will therefore be "unique" and thus left unmerged.
2. On-the-fly merging happens on every `interval -> overlapping …
> Bugfix: strict interval matching fixed

- tests/unit_tests_statistics.py
- tiny/rna/counter/statistics.py
Closes #152 
The procedure for determining this count from collapsed FASTA files has been improved. The old approach would fail if, for some reason, the length of the last sequence was over `75 - (log(COUNT) + log(INDEX) + 11)`. MMapped files support in-memory rfind without guessing at the final record's length, so it is much more succinct and reliable to use them instead.
> Bugfix: unique sequence off-by-one count corrected in summary_stats.csv reports

- tests/unit_tests_features.py
- tests/unit_tests_hts_parsing.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
Now that strand information is embedded in feature record tuples, it is no longer necessary to maintain a stranded GenomicArray for storing features. This also means that FeatureCounter.assign_features() no longer needs to perform two lookups for each alignment (one for each strand). This 50% reduction in calls to StepVector.get_steps() translates to a decent reduction in runtime.
The dataset I have been using for casual benchmarking:
- 10 SAM files with a total of 57,281,310 alignments (3.09 gb)
- A reduced WS230 GFF3 file with 21,808 features
- A permissive ruleset with 5 rules of equal hierarchy:
|Select for...|with value...|Alias by...|Hierarchy|Strand (sense/antisense/both)|5' End Nucleotide|Length|Match  |
|-------------|-------------|-----------|---------|--------------------------- …
> Counter: strandless lookup optimization

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/templates/run_config_template.yml
The command line option for Counter's `--decollapse` option has been added to the Run Config files and CWL definitions.
The Run Config key `plot_vector_points` now correctly sets the corresponding command line option during pipeline execution.
Closes #157
> CWL: command line options added for decollapsed SAM, vectorized scatter points

- tiny/rna/counter/features.py
- tiny/rna/counter/statistics.py
Closes #156 
This PR also includes the following additional bugfix (now updated in the issue-158 description):
Previously the determination for "Single/Multiple Features" counted the assignment of the same feature at multiple loci as a "multiple feature" assignment. This is also true for "Sequences Assigned to _". That means for sequences with one unique feature assignment at multiple loci, their counts were incorrectly added to the "multiple feature" stat. This is no longer the case; the determination for "single/multiple" now only considers the total UNIQUE features assigned to each sequence.
> Counter: 'Reads Assigned to Single/Multiple Feature(s)' semantics changed

- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/templates/tinyrna-light.mplstyle
The font for the Log2 subscript character now matches the surrounding font. Previously the subscript character used an uncommon font since it is inline mathtext. This prevents missing font errors when opening PDFs for editing.
Closes #161
> Plotter: Log2 subscript character font

- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/statistics.py
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
Counter now produces an additional 5'NT/length distribution matrix for assigned reads. This new output has "assigned_nt_len_dist" appended to its name. The previous length matrix output has been retained and now has "mapped_nt_len_dist" appended to its name.
Corresponding plots are produced by Plotter, and follow the same naming convention. len_dist plot titles now indicate which distribution subtype they display. An additional command line input was NOT created for these new plots; they are provided using the same "--len-dist" option. Plotter has no expectation that the "assigned_nt_len_dist" input will be provided. This PR is also backwards compatible with the old naming convention. If an nt_len_dist input is provided using the old naming convention, the outputs will also follow the old …
> Counter and Plotter: new 5'NT/length distributions for assigned reads

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/bowtie.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/templates/run_config_template.yml
Closes #160 
Closes #177 
Options added to CWL and Run Config:
- --best
- --strata
- --seedmms
- --seedlen
Options removed from Run Config and Workflow:
- fasta
- fastq
- sam
The `norc` option had a partial CWL implementation. It has also been corrected.
> CWL: new bowtie options, small improvements to bowtie Run Config

- START_HERE/run_config.yml
- conda/environment.yml
The default trim value was incorrectly set in the START_HERE Run Config. All other Run Config templates had the correct value.
> Collapser: default trim value correction

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/statistics.py
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/resume.py
- tiny/templates/run_config_template.yml
Rule charts and class charts are now rendered as a horizontal bar chart rather than a pie chart + bar chart.
The following changes have been made to the *_charts:
- View limits are consistent across libraries for each run, just as they are in the scatter plots, and this view limit is determined by the largest proportion across libraries
- Bars are colored according to width using a continuous color map
- Percentage labels are lighter for smaller values and darker for larger values
- Percentage labels are vertically centered with the bar regardless of plot dimensions and group count. They also switch from right of terminus to left of terminus if the bar occupies more than 80% of the plot width
The following changes have been made to Counter's counts_by_rule.csv output:
- The index entry …
> Plotter: rule_charts for counts assigned per rule

- README.md
- START_HERE/features.csv
- doc/Counter.md
- tests/unit_tests_hts_parsing.py
- tiny/rna/counter/hts_parsing.py
**Case sensitivity** is no longer required in the `Select for...` and `with value...` columns. More specifically, case does not need to match when examining a feature's attributes for an identity match. The original capitalization of both the attribute key and value is retained after a match is found, so capitalization in Counter's outputs will not be affected by this change.
**The Class attribute** is no longer required to be present in each feature's column 9 attributes. If the attribute is missing, a default Class value of `_UNKNOWN_` will be assigned to the feature. This default assignment takes place before stage 1 selection, so users may also define rules that `Select for: Class, with value: _unknown_`
**The GFF2 / GTF** is now listed as a supported format in the documentation, and …
> Counter: relaxed GFF requirements

- START_HERE/run_config.yml
- tests/testdata/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/resume.py
- tiny/templates/run_config_template.yml
Improvements and options have been added for managing len_dist plot bounds. On the command line the min and/or max (first/last) lengths can be optionally specified with:
- **--len-dist-min**
- **--len-dist-max**
If either is unspecified, the unspecified bound is determined from the data's bounds on a per-subtype basis (i.e. the "Mapped" subtype bounds are determined separately from the "Assigned" subtype). Bounds, whether calculated or specified, are fixed across all plots for each subtype.
Run Config entries have been added for user specification:
- `plot_len_dist_min`
- `plot_len_dist_max` 
If either of these values are unassigned, the workflow will first fall back to the corresponding entries for fastp (`length_required` and `length_limit`). These fastp values are also optional, so if …
> Plotter: improvements and options for handling min and/or max lengths in len_dist plots

- tiny/rna/counter/statistics.py
The SummaryStats class now produces the `summary_stats.csv` report when pipeline outputs from fastp and Collapser are unavailable. Conditional stats are now reported on a per-library basis when the library's pipeline outputs are available. Conditional stats are dropped from the output table when they are unable to be collected from all libraries.
This means that SummaryStats' Mapped Reads stat will be available for other MergedStats classes, like RuleCounts and for `norm_counts.csv` in FeatureCounts. RuleCounts has been updated to reflect these changes.
Closes #195
> Counter: more complete Summary Stats reporting when pipeline stats inputs are unavailable

- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/statistics.py
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
This PR introduces proper handling of non-nucleotide bases in SAM files. If present, these bases are now reported in corresponding nt_len_dist tables, and are shown in len_dist plots with a gray color.
This PR also includes a minor bugfix for how Plotter parses condition_and_rep from nt_len_dist filenames
> Counter and Plotter: N bases are now reported and plotted (if present) in len_dist outputs

- doc/Counter.md
- tests/unit_tests_features.py
- tests/unit_tests_hts_parsing.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/matching.py
- tiny/rna/util.py
Wildcard keywords are now allowed in the `Select for...` and `with value...` fields. Wildcards are allowed in _either_ field or both. These keywords have been extended to include an asterisk character "*" and an empty cell, and this applies to all selectors which allow wildcard keywords.
The Wildcard class now follows a singleton design pattern which is much more inline with its meaning.
> Counter: support for wildcard keywords in Identity selectors

- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
The longest dimension (width/height) of each plot is now the same across plots in order to make fonts sizes appear more consistent. Font sizes have also been made... more consistent.
In some cases the proportions charts will have percentage labels that differ from the other font sizes. This is to accommodate bars that span 80% of the plot space or more because the labels are placed on the bars themselves rather than to the right. It looks bad if the font size is larger than the bar in these cases, so the font size is the minimum between the default size and the bar's height in points.
> Plotter: normalized plot fonts and normalized longest dimension of plot size

- setup.sh
If the host environment requires a Miniconda installation, this PR introduces a fix to prevent crashing on subsequent uses of `conda` in setup.sh. I've also pinned the Miniconda installer version rather than using the "latest" so that installations are more reliable/predictable moving forward.
Closes #212
> Bugfix for Miniconda installation in setup.sh

- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
Improvements in `sample_avg_scatter_by_dge*` plots:
- Color assignment for classes is now consistent across samples
- The legend is now (properly) sorted alphabetically rather than by group size
- Groups are still plotted in descending order of size so that the least abundant classes are plotted on top
- If the number of groups exceeds the number of colors in the stylesheet, tiny-plot will switch to a 20 item color map. The color map will repeat if more than 20 groups need to be plotted.
The code in plotterlib.scatter_grouped() has been refined, and the code in plotter.scatter_dge() has been slightly simplified.
Closes #219
> tiny-plot: consistent color assignment across classes, detail improvements in legend and codebase

- tiny/rna/counter/statistics.py
The SummaryStats class now properly handles gzipped tiny-collapse outputs when the user elects to have them produced. Previously, it assumed all tiny-collapse outputs to be plaintext
Closes #221
> tiny-count: fix handling of gzipped tiny-collapse outputs for SummaryStats

- README.md
Bioconductor components which are fetched by post-link.sh currently fail on installation because they have been moved. The target urls return HTTP 302 when referenced, and since post-link.sh does not use curl with the -L option, the redirect isn't followed and the installation script errors out. 
Please note that post-link.sh is a component specifically of Bioconductor packages, and that the root cause of the issue is out of our control but Bioconda is actively migrating all Bioconductor packages to fix the issue.
In the meantime, I am changing README.md to direct users to install via release 1.0.1 rather than fetching the master branch. This release did not use the Bioconductor packages hosted on Bioconda, so the issue is avoided.
> Temporary solution for Bioconductor recipes on Bioconda while they implement a fix

- conda/conda-linux-64.lock
- conda/conda-osx-64.lock
- conda/environment.yml
- conda/update-lockfiles.sh
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/counter.py
- tiny/rna/counter/statistics.py
Updated the URL in lockfiles for bioconductor-genomeinfodbdata to use the latest build, which fixes an issue in the recipe that prevented tinyRNA installation (many thanks to Tai for tracking this down).
I've also added a script to automate the process of updating the lockfiles per the contents of environment.yml, which will also include updated build numbers for the entire dependency tree. The script can be used to remedy future issues like this. Note that it was NOT used for the lockfile changes included in this PR since the build updates were quite extensive and I have time limitations for testing this week
tiny-count's --features-csv short argument was changed from -c to -f when 3rd party SAM file support was added. This change was made hastily and a bit last minute, and since it was …
> Installation issue fix, lockfile creation script, and tiny-count command line argument updates

- START_HERE/features.csv
- START_HERE/run_config.yml
- doc/Configuration.md
- doc/Parameters.md
- doc/tiny-count.md
- tests/unit_test_helpers.py
- tests/unit_tests_counter.py
- tests/unit_tests_hts_parsing.py
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/configuration.py
- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/matching.py
- tiny/rna/counter/validation.py
- tiny/templates/features.csv
- tiny/templates/paths.yml
- tiny/templates/run_config_template.yml
**Config File Changes:**
The `counter_source_filter` and `counter_type_filter` have been moved out of the Run Config and into the Features Sheet. This means that `Source/Type Filters` are specific to their rule/row. They have been absorbed into Stage 1 selection, so we now say the targets of Stage 1 selection are GFF columns 2, 3, and 9.
**Command line argument changes:**
The `--source-filter` and `--type-filter` arguments have been removed from tiny-count.
**Codebase improvements:**
If the Features Sheet contains column headers from a previous version of tinyRNA, a helpful error message is produced that lets the user know what changed, where to read about it, and what to do to make the error go away. This is better than the generic missing/unknown column header that would otherwise be …
> Pipeline: new location and scope for GFF Source Filters and Column Filters

- tiny/rna/collapser.py
- tiny/rna/counter/validation.py
- tiny/rna/util.py
GFFValidator will now validate chromosomes using gzipped reference genome FASTAs (if appropriate), and will no longer produce a warning under these circumstances
> GFFValidator: adding support for gzipped reference genome files

- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/configuration.py
- tiny/rna/resume.py
This PR allows for certain keys in the Paths File to be changed between resume runs. This addresses a bug where changes to the parameters in the Paths Sheet aren't integrated into the processed Run Config when executing resume runs. This PR also addresses a notice (not warning or error) issued by cwltool regarding similar parameter names in tiny-plot.cwl
> Version 1.2 prep: allow changes in Paths File between resume runs

- doc/Parameters.md
- tiny/entry.py
- tiny/rna/collapser.py
- tiny/rna/counter/counter.py
- tiny/rna/plotter.py
- tiny/rna/util.py
Closes #260
Note: branch issue-260 is derived from issue-258. PR #259 needs to be closed first, then this PR needs to have its base branch toggled in order to display an accurate record of file changes
> Pipeline: better help string for `tiny` command

- tiny/rna/tiny-deseq.r
> tiny-deseq.r: bugfix: proper handling of control conditions that contain forbidden characters

- tests/unit_tests_configuration.py
- tiny/rna/configuration.py
- tiny/rna/util.py
R has strict character requirements for "syntactically valid" names in a variety of contexts, including column names. Sample group names therefore must undergo a translation to a valid form before analysis in tiny-deseq.r. This translation creates an opportunity for different group names to end up with the same "safe name", which will lead to a crash. For example, the group names `a-b` and `a+b` will both translate to `a.b`. 
This PR adds an additional validation step to the SamplesSheet class to proactively catch these namespace collisions at pipeline startup. It provides a helpful error message that lists all collisions and groups them by shared "safe name"
Closes #266
> tiny-config: SamplesSheet: validate group names to avoid namespace collisions in R

- tests/unit_tests_plotter.py
- tiny/rna/plotterlib.py
The routine for placing scatter plot tick labels is now more robust when the plotted range is very small or very large. "Every other _n_" label placement now adjusts to the plot window rather than being a fixed _n_ = 3. Labels are no longer suppressed at the origin; this was originally done when we were using exponent labels which are much wider. Labels at the upper end of the axis are placed more liberally. All in all, these changes produce tick labels with more comfortable density under a wider range of plot window sizes.
This is demonstrated in the below animation, which uses a rolling, expanding window:
Closes #265
> tiny-plot: sanity improvements in scatter plot tick labels

- README.md
- START_HERE/tiny-count_TUTORIAL.md
- START_HERE/tinyRNA_TUTORIAL.md
- tests/testdata/collapser/helpstring.txt
- tests/unit_tests_configuration.py
- tests/unit_tests_entry.py
- tests/unit_tests_plotter.py
- tiny/entry.py
- tiny/rna/configuration.py
- tiny/rna/counter/counter.py
This PR adds an additional tutorial file to the START_HERE directory for `tiny-count`. The get-templates functionality has been consolidated so that it can be shared by both the `tiny` and `tiny-count` commands, and its logic has been updated so that existing template files in the CWD are not overwritten. 
If a template file already exists, no files are copied and the user is instructed to rename or remove the specific conflicting files. I chose this route over simply appending a (#) to the filename because doing so might require that the user also update the corresponding entries in the Paths File, and this might lead to a poor user experience at the onset of use.
This PR also updates some unrelated unit tests
> tiny-count: tutorial, project: refactor get-templates logic

- START_HERE/run_config.yml
- dev/macos_pycharm_r_plugin_patch.py
- doc/Parameters.md
- doc/tiny-plot.md
- setup.py
- tests/testdata/config_files/run_config_template.yml
- tiny/cwl/tools/tiny-plot.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/tiny-deseq.r
- tiny/templates/run_config_template.yml
This PR adds options for user-specified min and/or max view limits for DGE scatter plots, which are specified as log2 count values and can be whole or fractional numbers. It also includes minor changes to output filenames from tiny-deseq and tiny-plot to be consistent with the "experimental condition vs. control condition" order used in DGE scatter plots. Plot titles and axis labels in bar plots have been updated to have sentence case, to be consistent with the scatter plots.
The following minor bugs have also been addressed:
- A bug in lower view limit calculation that occurs when the feature with the lowest count also has a count of zero in another group/replicate (for DGE scatter plots and replicate scatter plots, respectively). Under certain conditions this could lead to the lowest …
> tiny-plot: user-defined view limits for DGE scatter plots, and other consistency improvements

- START_HERE/run_config.yml
- tests/testdata/config_files/run_config_template.yml
- tests/unit_tests_hts_parsing.py
- tiny/cwl/workflows/preprocessing.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/entry.py
- tiny/rna/compatibility.py
- tiny/rna/configuration.py
- tiny/rna/resume.py
- tiny/templates/compatibility/run_config_compatibility.yml
- tiny/templates/run_config_template.yml
The new subdirectory `logs` has been added to the Run Directory. Log files for all workflow steps will be stored here rather than in their respective step subdirectories. This allows for preservation of logs that are produced by failing workflow steps, which is critical for troubleshooting.
Closes #275
> Pipeline: log file preservation for failing steps

- START_HERE/paths.yml
- tests/testdata/config_files/paths.yml
- tests/unit_tests_configuration.py
- tests/unit_tests_counter.py
- tests/unit_tests_hts_parsing.py
- tests/unit_tests_stepvector.py
- tests/unit_tests_validation.py
- tiny/rna/configuration.py
- tiny/rna/counter/counter.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/validation.py
- tiny/rna/resume.py
- tiny/templates/paths.yml
tiny-count can now perform sequence-based counting as an alternative to feature-based counting. This is useful to users who don't have GFF annotations for their experiment, or users who want to count reads against a set of known sequences.
tiny-count automatically switches to this counting mode when a user's Paths File doesn't have any GFFs listed.
tinyRNA no longer requires GFF files at pipeline startup.
In sequence-based counting mode, Stage 1 selectors cannot be evaluated and are therefore ignored (`Select for...`, `with value...`, `Classify as...`, `Source Filter`, and `Type Filter` ). Stage 2 and Stage 3 are evaluated as they would be for feature-based counting.
In sequence-based counting mode, "feature" intervals are defined by the `@SQ` headers of input SAM files. These headers …
> tiny-count: support for sequence-based read counting

- tests/unit_tests_configuration.py
- tests/unit_tests_features.py
- tests/unit_tests_matching.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/matching.py
Overlap selector definitions have been extended to optionally accept 2 numerical parameters that shift the 5' and 3' ends of matching feature intervals. Alignments are then evaluated using this shifted interval in Stage 2 selection. They have the following syntax:
```
selector, M, N
M = shift value for 5' end
N = shift value for 3' end
```
- **Positive** values shift the specified end in the **3'** direction
- **Negative** values shift the specified end in the **5'** direction
- If either parameter is provided, the other must also be provided
- Zero is also an accepted shift value
Shifting might produce an illegal interval. When this happens, the offending match (the feature-rule pair) is omitted from Stage 2 and 3 selection, but the feature's other matches remain. Illegal intervals …
> tiny-count: shift parameters for overlap selectors

- tiny/rna/plotter.py
- tiny/rna/plotterlib.py
- tiny/rna/util.py
Scatter plot legends are now sorted by natural order while preserving the intended point layer order (groups with fewest points are plotted on top of the stack).
This PR also includes a number of reliability improvements:
- Fixed an edge case that occurs when the outgroup has all zero counts in one or both conditions. Previously this would result in the outgroup having an entry in the legend without any points being plotted
- Fixed an edge case that occurs when there is no outgroup, and the first group has all zero counts in one or both conditions. Previously this first plotted group wouldn't be recognized as a zero count group, so it would have an entry in the legend without any points being plotted
- Properly handling an empty scatter plot when neither the outgroup nor the other groups …
> tiny-plot: legend sorted by natural order, other reliability improvements

- doc/tiny-count.md
- tests/unit_tests_hts_parsing.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/validation.py
Counts for individual reference sequences are subset by `Classify as...` values in sequence-based counting mode. Unit tests have been added for the ReferenceSeqs class.  
In unit_tests_hts_parsing.py, I split up the gigantic test suite by target class. This is a good thing but it makes the diff wildly out of control on this PR because I didn't commit the reorganization before adding the ReferenceSeqsTests class.
Additionally, both GFFValidator and SamSqValidator classes now report when validation has finished
> tiny-count: adding classifier support to sequence-based counting

- tiny/rna/configuration.py
CSVReader now replaces the ellipsis character, which Microsoft Excel autocorrects from three periods, in header lines. The corrected file is written to disk because there isn't a good way to do this on-the-fly.
Rows that are empty/whitespace don't have any useful meaning in our config files, and they cause problems while parsing. These rows are now skipped.
Closes #288
> CSVReader: ellipsis character replacement, empty rows are skipped

- tiny/cwl/tools/tiny-collapse.cwl
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/tools/tiny-plot.cwl
The workflow runner now uses the longer/descriptive flag when executing `tiny-collapse`, `tiny-count`, and `tiny-plot`. This doesn't have a functional purpose. It is only intended to provide more informative output during pipeline execution.
> Pipeline: longer/descriptive flags in tiny-* CommandLineTool specifications

- START_HERE/features.csv
- doc/Configuration.md
- doc/tiny-count.md
- setup.py
- tests/testdata/config_files/features.csv
- tests/testdata/counter/validation/sam/sq_headers.sam
- tests/unit_test_helpers.py
- tests/unit_tests_counter.py
- tests/unit_tests_features.py
- tests/unit_tests_hts_parsing.py
- tests/unit_tests_matching.py
- tests/unit_tests_validation.py
- tiny/rna/configuration.py
- tiny/rna/counter/features.py
- tiny/rna/counter/hts_parsing.py
- tiny/rna/counter/parsing/__init__.py
- tiny/rna/counter/parsing/alignments.pyx
- tiny/rna/counter/validation.py
- tiny/templates/features.csv
This PR introduces a new selector for tiny-count: Mismatches. It is used for placing constraints on the edit distance between an alignment and the reference, and it is evaluated in Stage 2 after the Overlap selector. Users can specify ranges, lists, wildcards, and single values in this column.
Edit distance is determined from the NM tag. If the first alignment in a SAM file is missing the tag, then the edit distance for all subsequent alignments is calculated from the CIGAR string's I, D, and X operations. If the first alignment has an NM tag and a subsequent alignment does not, then the subsequent alignment's edit distance assumes a default value of zero.
The former function for producing alignment dictionaries, SAM_reader._parse_alignments(), has been converted to a standalone Cython …
> tiny-count: new selector: Mismatches

- README.md
- START_HERE/run_config.yml
- tests/testdata/config_files/run_config_template.yml
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/counter/statistics.py
- tiny/templates/run_config_template.yml
- Classifier-related bugs have been fixed
- Alignment tables are now produced as CSVs rather than TSVs
- Alignment tables now include the alignment's chromosome as well as the number of feature candidates that were available for selection at the beginning of Stage 2. Strand is also represented as +/-/. rather than True/False/None.
- Output files have been renamed: 
- ...aln_table.txt ---> ...alignment_table.csv
- alignment_diags.csv ---> assignment_diags.csv
Please close PR #298 first
Closes #299
> tiny-count: bugfixes and improvements in diagnostic outputs

- README.md
- START_HERE/run_config.yml
- doc/Configuration.md
- doc/Parameters.md
- doc/tiny-count.md
- setup.py
- tests/testdata/config_files/run_config_template.yml
- tiny/cwl/tools/tiny-count.cwl
- tiny/cwl/workflows/tinyrna_wf.cwl
- tiny/rna/configuration.py
- tiny/rna/counter/counter.py
- tiny/rna/counter/statistics.py
- tiny/rna/plotter.py
- tiny/templates/compatibility/run_config_compatibility.yml
- tiny/templates/run_config_template.yml
The two normalization-by-hits options, by genomic hits and feature hits, can now be disabled both independently and in tandem. When either normalization step is disabled, two new stats are reported in summary stats in place of Mapped Reads:
- **Non-normalized Mapped Reads**: the sum of assigned and unassigned reads according to the normalization config
- **Normalized Mapped Reads**: the true read count
tiny-plot automatically uses the appropriate stat for calculating proportions in rule_charts and class_charts.
The counts reported in all output stats files are now thoroughly checked for internal consistency. Discrepancies are reported to console with a clear description rather than being treated as an error. If alignment stats and summary stats have internal disagreement, a checksum table …
> tiny-count: option for normalization by genomic hits, improvements in stats collection precision 

- setup.py
Addresses the following error observed at runtime on Linux platforms:
```
ImportError: 
[...] alignments.cpython-39-x86_64-linux-gnu.so: undefined symbol: bam_aux2i
```
> setup.py: bugfix for building Pysam-dependent Cython extensions on Linux platforms

- tiny/rna/configuration.py
An empty `run_directory` value in the Paths File no longer produces processed Run Configs with incomplete relative paths.
Closes #320
> pipeline: correct handling of optional run_directory suffix in Paths File

- .github/ISSUE_TEMPLATE.md
- README.md
This PR cleans up the issue template and updates the instructions for attaching diagnostic information.
It also provides a minor correction to the ordering of alias values in the tiny-count output feature_counts.csv. If a feature has multiple aliases associated with it, the values will be sorted in the Feature Name column. The order of the values does not reflect their original order in annotations, nor does it reflect the order in which alias keys were defined in the Paths File.
> Update issue template
